# Generated by Django 5.2.8 on 2025-11-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('STUDENT', 'student'), ('STAFF', 'staff'), ('PARENT', 'parent')], default='STUDENT', max_length=20),
        ),
    ]
