# Generated by Django 5.2.8 on 2025-11-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('professor', 'Professor'), ('ta', 'Teaching Assistant'), ('staff', 'Staff'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
